s="baba Ka beta Beta"
print(s)
print(s.capitalize())
print(s.title())
print(s.casefold())
print(s.lower())
print(s.upper())
print(s.count("baba"))
print(s.count("@"))
print(s.find("beta"))
print(s.find("@"))
print(s.index("K"))
print(s.replace("beta","bhaukal"))
print(s)
s=s.replace("beta","bhaukal")
print(s)
print(s.swapcase())
