print("let the quadratic equation be the form of ax^2+bx+c")
a=float(input("the value of a="))
b=float(input("the value of b="))
c=float(input("the value of c="))
d=((b*b)-(4*a*c))
e=pow(d,0.5)
root1= (-b+e)/(2*a)
root2= (-b-e)/(2*a)
print("root 1=" + str(root1))
print("root 2="+str(root2))
